//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TomosurgeryAlpha.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TomosurgeryAlpha.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _469_307_2 {
            get {
                object obj = ResourceManager.GetObject("_469_307_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.01107046
        ///0.0108469
        ///0.01128872
        ///0.01115461
        ///0.01095115
        ///0.01105269
        ///0.01132603
        ///0.01168032
        ///0.01161607
        ///0.01214531
        ///0.01166676
        ///0.01120227
        ///0.01082802
        ///0.01038883
        ///0.009777239
        ///0.009153175
        ///0.008734787
        ///0.008445463
        ///0.008292566
        ///0.007979668
        ///0.007797877
        ///0.007581747
        ///0.007442257
        ///0.007303071
        ///0.007189602
        ///0.006957936
        ///0.006777858
        ///0.006427872
        ///0.005891446
        ///0.005179512
        ///0.005176149
        ///0.004904296
        ///0.00503278
        ///0.005778051
        ///0.005989512
        ///0.00646752
        ///0.006571103
        ///0.006520675
        ///0.006683055
        ///0.006656394
        ///0.0066426 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string _4mm_dose {
            get {
                return ResourceManager.GetString("_4mm_dose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector Configuration: 
        ///44444444
        ///Resolution: 
        ///0.25
        ///Shot Location (x,y,z): 
        ///100
        ///100
        ///100
        ///161
        ///.
        /// </summary>
        public static string _4mm_head {
            get {
                return ResourceManager.GetString("_4mm_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap BWheatmap3 {
            get {
                object obj = ResourceManager.GetObject("BWheatmap3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap carbon_fiber_background_wallpaper_2560x1600 {
            get {
                object obj = ResourceManager.GetObject("carbon_fiber_background_wallpaper_2560x1600", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap carbon_fiber_wallpaper_1280x960 {
            get {
                object obj = ResourceManager.GetObject("carbon_fiber_wallpaper_1280x960", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] dicomdictionary {
            get {
                object obj = ResourceManager.GetObject("dicomdictionary", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap gunmetal_24a893 {
            get {
                object obj = ResourceManager.GetObject("gunmetal_24a893", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap metbase {
            get {
                object obj = ResourceManager.GetObject("metbase", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap seashell {
            get {
                object obj = ResourceManager.GetObject("seashell", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Test_Image_Color_Response_0_512x512_No_Noise {
            get {
                object obj = ResourceManager.GetObject("Test_Image_Color_Response_0_512x512_No_Noise", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap X_Ray_of_a_male_skeleton_DJ_spinning_records_on_a_couple_of_xray_turntables {
            get {
                object obj = ResourceManager.GetObject("X_Ray_of_a_male_skeleton_DJ_spinning_records_on_a_couple_of_xray_turntables", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
